%% AI Project - Breast Cancer Wisconsin (Diagnostic) Classification in MATLAB
% Bonus requirement: MATLAB implementation (real, non-Iris dataset)
% Models: Support Vector Machine (fitcsvm) and Decision Tree (fitctree)
%
% Requires: Statistics and Machine Learning Toolbox
% Input file: breast_cancer_dataset.csv (generated by train_models_bc.py,
%             place it in the same folder as this script before running)

clear; clc; close all;

%% 1) Load dataset
T = readtable('breast_cancer_dataset.csv');
disp('Dataset preview:');
disp(head(T));

X = table2array(T(:, 1:end-1));
y = categorical(T.target);  % 0 = malignant, 1 = benign
featureNames = T.Properties.VariableNames(1:end-1);

fprintf('Samples: %d, Features: %d, Classes: %d\n', ...
    size(X,1), size(X,2), numel(categories(y)));

%% 2) Train / test split (80/20, stratified) + standardization
rng(42);
cv = cvpartition(y, 'HoldOut', 0.2, 'Stratify', true);

X_train = X(training(cv), :);
X_test  = X(test(cv), :);
y_train = y(training(cv));
y_test  = y(test(cv));

mu = mean(X_train);
sigma = std(X_train);
X_train_s = (X_train - mu) ./ sigma;
X_test_s  = (X_test  - mu) ./ sigma;

%% 3) MODEL 1: SVM (binary classification, RBF kernel)
svmModel = fitcsvm(X_train_s, y_train, 'KernelFunction', 'rbf', ...
    'Standardize', false, 'BoxConstraint', 1);

y_pred_svm = predict(svmModel, X_test_s);
acc_svm = sum(y_pred_svm == y_test) / numel(y_test);
fprintf('\n=== SVM Results ===\n');
fprintf('Test Accuracy: %.4f\n', acc_svm);

figure('Name', 'SVM Confusion Matrix');
confusionchart(y_test, y_pred_svm, 'Title', ...
    sprintf('SVM Confusion Matrix (acc=%.2f)', acc_svm));
saveas(gcf, 'matlab_svm_confusion.png');

%% 4) MODEL 2: Decision Tree
treeModel = fitctree(X_train_s, y_train, 'MaxNumSplits', 10);

y_pred_tree = predict(treeModel, X_test_s);
acc_tree = sum(y_pred_tree == y_test) / numel(y_test);
fprintf('\n=== Decision Tree Results ===\n');
fprintf('Test Accuracy: %.4f\n', acc_tree);

figure('Name', 'Decision Tree Confusion Matrix');
confusionchart(y_test, y_pred_tree, 'Title', ...
    sprintf('Decision Tree Confusion Matrix (acc=%.2f)', acc_tree));
saveas(gcf, 'matlab_tree_confusion.png');

figure('Name', 'Decision Tree Structure');
view(treeModel, 'Mode', 'graph');

%% 5) Accuracy comparison plot
figure('Name', 'Accuracy Comparison');
bar(categorical({'SVM','Decision Tree'}), [acc_svm, acc_tree]);
ylim([0 1]);
ylabel('Test Accuracy');
title('MATLAB Model Accuracy Comparison - Breast Cancer Dataset');
saveas(gcf, 'matlab_accuracy_comparison.png');

%% 6) Save summary
fid = fopen('matlab_results_summary.txt', 'w');
fprintf(fid, 'SVM Test Accuracy: %.4f\n', acc_svm);
fprintf(fid, 'Decision Tree Test Accuracy: %.4f\n', acc_tree);
fclose(fid);

disp('Done. Figures and matlab_results_summary.txt saved to current folder.');
