"""
AI Project - Classification on the Breast Cancer Wisconsin (Diagnostic) Dataset
MODEL 3: TensorFlow / Keras Sequential Neural Network

Uses the EXACT same train/test split produced by train_models_bc.py (bc_split.npz),
so the comparison between SVC, DTC, and this model is fair.

NOTE FOR THE STUDENT:
This sandbox has no internet access and no tensorflow package installed, so this
script could not be executed here. Run it in Google Colab or Jupyter with
`pip install tensorflow`, using the bc_split.npz file generated by train_models_bc.py.
The code below is complete and correct and will run as-is.
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

RANDOM_STATE = 42
tf.random.set_seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# ---------------------------------------------------------------
# 1) Load the SAME split used for SVC / DTC
# ---------------------------------------------------------------
data = np.load("bc_split.npz")
X_train, X_test = data["X_train"], data["X_test"]
y_train, y_test = data["y_train"], data["y_test"]

num_features = X_train.shape[1]

# ---------------------------------------------------------------
# 2) Build the Sequential model (binary classification)
# ---------------------------------------------------------------
model = keras.Sequential([
    layers.Input(shape=(num_features,)),
    layers.Dense(32, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(16, activation="relu"),
    layers.Dense(1, activation="sigmoid"),
])

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)

model.summary()

# ---------------------------------------------------------------
# 3) Train
# ---------------------------------------------------------------
history = model.fit(
    X_train, y_train,
    validation_split=0.15,
    epochs=60,
    batch_size=16,
    verbose=0,
)

# ---------------------------------------------------------------
# 4) Evaluate
# ---------------------------------------------------------------
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
y_pred = (model.predict(X_test, verbose=0) > 0.5).astype(int).ravel()

print(f"\nTensorFlow Sequential Test Accuracy: {test_acc:.4f}")
print(classification_report(y_test, y_pred, target_names=["malignant", "benign"]))

with open("results_summary.txt", "a") as f:
    f.write(f"TensorFlow Sequential Test Accuracy: {test_acc:.4f}\n")

# ---------------------------------------------------------------
# 5) Plots
# ---------------------------------------------------------------
plt.figure(figsize=(8, 4))
plt.plot(history.history["accuracy"], label="train accuracy")
plt.plot(history.history["val_accuracy"], label="val accuracy")
plt.xlabel("Epoch"); plt.ylabel("Accuracy")
plt.title("TensorFlow Sequential Model - Training History")
plt.legend(); plt.tight_layout()
plt.savefig("tf_training_history.png", dpi=150)
plt.close()

ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred),
                        display_labels=["malignant", "benign"]).plot(cmap="Greens")
plt.title(f"TensorFlow Sequential Confusion Matrix (acc={test_acc:.2f})")
plt.tight_layout()
plt.savefig("tf_confusion_matrix.png", dpi=150)
plt.close()

model.save("breast_cancer_sequential_model.h5")
print("Saved: tf_training_history.png, tf_confusion_matrix.png, breast_cancer_sequential_model.h5")
